#!/bin/sh /etc/rc.common

START=40
STOP=99

# start after USB (39) but before other apps possibly installed on external disk

. /lib/functions/mount.sh

start() {
    # Delete USB tmp directory
    mount | grep /dev/sda1  | grep /mnt/tmp
    if [ $? ]; then
        rm -rf /mnt/tmp/*
        cp -a /tmp/* /mnt/tmp/
        if [ -h /var ]; then
            mount | grep /dev/sda2  | grep /mnt/var
            if [ $? ]; then
                cp -a /tmp/* /mnt/var
            fi
        fi
    fi

    # # Create var content if not exist
    # mount | grep /dev/sda2  | grep /mnt/var
    # if [ $? ]; then
    #     rm -rf /var
    #     mkdir /var
    # fi


    # # Mount
    # umount -l /tmp
    # mount /mnt/tmp /tmp -o move
    # chmod 777 /tmp
    # logger -p info "TMP USB FILE IS OK"
    # mount /mnt/var /var -o move
    # chmod 777 /var
    # logger -p info "VAR USB FILE IS OK"
}

stop() {
    logger -p info "TMP & VAR USB FILE IS STOPPED"
}
